### Site info:
title: Meraklının Sayfası
tagline: Hey NSV!
author: Mustafa Asım Altınışık
email: mustafa@altinisik.net
description: "Meraklının Sayfası" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "MustafaAltınışık, blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/mustafa@altinisik.net" # the base hostname & protocol for your site
locale: tr_TR

### Personal info and site tools info:
github_username:  mustafa-altinisik
disqus_shortname: mustafaaltnk 
twitter_username: mustafa_altnisk
instagram_username: m.altinisik
#favicon:     "/images/favicon.ico"
aboutme: Merhaba, ben Mustafa Altınışık. ASO Teknik Koleji Elektrik Elektronik bölümü öğrencisiyim. Yaptığım projeleri yayınladığım ve çeşitli faydalı bilgiler paylaştığım  Bloguma hoşgeldiniz.Keyfini çıkartın. 
aboutme_photo: https://www.gravatar.com/avatar/ade4610d6e8692c99d9534105405d89f# your photo.
google_analytics_key: UA-79586838-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "tr" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp) and Polish (pl)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
    tr:
      Aboutme: "Hakkımda"
      Archives: "Arşivler"
      Blogroll: "Blog"
      Categories: "Kategoriler"
      Copyright_Notice: "Aman Dikkat!"
      Recent_Posts: "Makaleler"
      Tags: "Etiketler"
      Previous: "Önceki"
      Next: "Sonraki"
      PostedInCategories: "Kategoriler"
      Taggedwith: "etiketler:"
      PostDate: "tarih "
      Google_search: "Site Araması"
      Home: "Ana Menü"
      About: "Hakkımda"
      Guestbook: "Ziyaretçi Defteri"
      Subscribe: ""
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"
      Guestbook: "留言"
      Subscribe: "订阅"
    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: "サイト内検索"
      Home: "ホーム"
      About: "このブログについて"
      Guestbook: "メッセージ"
      Subscribe: "購読"
    pl:
      Aboutme: "O mnie"
      Archives: "Archiwum"
      Blogroll: "Odnośniki"
      Categories: "Kategorie"
      Copyright_Notice: "Prawa autorskie"
      Recent_Posts: "Najnowsze wpisy"
      Tags: "Tagi"
      Previous: "Starsze"
      Next: "Nowsze"
      PostedInCategories: "Kategoria"
      Taggedwith: "tagi"
      PostDate: "on "
      Google_search: "Wyszukiwarka"
      Home: "Strona główna"
      About: "O mnie"
      Guestbook: "Księga gości"
      Subscribe: "Subskrypcja"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Mustafa Altınışık
        href: http://mustafa.altinisik.net
        title: Mustafa Altınışık'ın Blogu

### Build settings
#markdown: kramdown
#highlighter: pygments
#kramdown:
#        input: GFM
#        syntax_highlighter: rouge
#gems: [jekyll-paginate]
#paginate: 5
#excerpt_separator: <!-- Daha Fazla -->
### Build settings
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]
paginate: 10
excerpt_separator: <!-- more -->
